login:
  identity:
    SessionType: Normal
    InitiatorName: iqn.2004-10.com.ubuntu:01:c676ed18968f
    InitiatorAlias: ubuntu
    TargetName: iqn.2025-08.example:disk0

  auth:
    AuthMethod: None

  integrity:
    HeaderDigest: None
    DataDigest: None

  flow:
    MaxRecvDataSegmentLength: 262144
    MaxBurstLength: 16776192
    FirstBurstLength: 262144

  write_flow:
    InitialR2T: Yes
    ImmediateData: No
    MaxOutstandingR2T: 1

  ordering:
    DataPDUInOrder: Yes
    DataSequenceInOrder: Yes

  recovery:
    ErrorRecoveryLevel: 1

  timers:
    DefaultTime2Wait: 2
    DefaultTime2Retain: 0

  limits:
    MaxConnections: 1

  extensions:
    IFMarker: "No"
    OFMarker: "No"
    X-TargetAlias: "iscsi-target-vm"

  transport:
    TargetAddress: 127.0.0.1:3260
    TargetPortalGroupTag: 1

runtime:
  MaxSessions: 2
  TimeoutConnection: 30
